const menuToggle=document.querySelector("#menu-toggle");
const navbar=document.querySelector("#navbar");
const navLinks=document.querySelectorAll(".nav-link");
if(menuToggle&&navbar){menuToggle.addEventListener("click",()=>{navbar.classList.toggle("open");const icon=menuToggle.querySelector("i");icon?.classList.toggle("fa-bars");icon?.classList.toggle("fa-xmark")});navLinks.forEach(link=>link.addEventListener("click",()=>{navbar.classList.remove("open");const icon=menuToggle.querySelector("i");icon?.classList.add("fa-bars");icon?.classList.remove("fa-xmark")}))}
const sections=document.querySelectorAll("main section[id]");
function updateActiveMenu(){const atPageEnd=window.innerHeight+window.scrollY>=document.documentElement.scrollHeight-2;const p=atPageEnd?document.documentElement.scrollHeight-1:window.scrollY+180;sections.forEach(section=>{const item=document.querySelector(`.nav-link[href="#${section.id}"]`);if(p>=section.offsetTop&&(p<section.offsetTop+section.offsetHeight||atPageEnd&&section===sections[sections.length-1])){navLinks.forEach(l=>l.classList.remove("active"));if(item)item.classList.add("active")}})}
if(sections.length){window.addEventListener("scroll",updateActiveMenu);updateActiveMenu()}
const observer=new IntersectionObserver(entries=>entries.forEach(entry=>{if(entry.isIntersecting){entry.target.classList.add("visible");observer.unobserve(entry.target)}}),{threshold:.12});document.querySelectorAll(".reveal").forEach(el=>observer.observe(el));
const skillTabs=document.querySelectorAll(".skill-tab"),skillContents=document.querySelectorAll(".skill-content");skillTabs.forEach(tab=>tab.addEventListener("click",()=>{skillTabs.forEach(i=>i.classList.remove("active"));skillContents.forEach(c=>c.classList.remove("active"));tab.classList.add("active");document.querySelector(`[data-content="${tab.dataset.category}"]`)?.classList.add("active")}));
const year=document.querySelector("#year");if(year)year.textContent=new Date().getFullYear();const header=document.querySelector(".header");if(header)window.addEventListener("scroll",()=>header.style.background=window.scrollY>40?"rgba(2, 12, 27, 0.92)":"rgba(2, 12, 27, 0.72)");
